table Products

	column 'Product ID'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Product ID

	column Product
		dataType: string
		summarizeBy: none
		sourceColumn: Product

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category

	column Subcategory
		dataType: string
		summarizeBy: none
		sourceColumn: Subcategory

	column 'List Price'
		dataType: double
		formatString: $#,0.00
		summarizeBy: none
		sourceColumn: List Price

	partition Products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Products.csv"), [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Product ID", type text}, {"Product", type text}, {"Category", type text}, {"Subcategory", type text}, {"List Price", type number}}, "en-US")
				in
				    Typed
