/// One row per order. 2024-01-01 to 2026-08-31.
table Orders

	/// Net sales after discount, USD.
	measure Revenue = SUM ( Orders[Net Sales] )
		formatString: $#,0
		displayFolder: Sales

	measure Cost = SUM ( Orders[COGS] )
		formatString: $#,0
		displayFolder: Sales

	measure 'Gross Profit' = [Revenue] - [Cost]
		formatString: $#,0
		displayFolder: Sales

	measure 'GP %' = DIVIDE ( [Gross Profit], [Revenue] )
		formatString: 0.0%
		displayFolder: Sales

	measure 'Order Count' = COUNTROWS ( Orders )
		formatString: #,0
		displayFolder: Sales

	/// Average order value.
	measure AOV = DIVIDE ( [Revenue], [Order Count] )
		formatString: $#,0.00
		displayFolder: Sales

	/// Same period last year.
	measure 'Revenue LY' = CALCULATE ( [Revenue], SAMEPERIODLASTYEAR ( Calendar[Date] ) )
		formatString: $#,0
		displayFolder: Last year

	measure 'Revenue YoY %' = DIVIDE ( [Revenue] - [Revenue LY], [Revenue LY] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Last year

	/// Monthly budget by category.
	measure 'Budget Sales' = SUM ( Budget[Amount] )
		formatString: $#,0
		displayFolder: Budget

	measure 'Vs Budget' = [Revenue] - [Budget Sales]
		formatString: +$#,0;-$#,0;0
		displayFolder: Budget

	measure 'Last Order Date' = CALCULATE ( MAX ( Orders[Order Date] ), REMOVEFILTERS () )
		formatString: yyyy-mm-dd
		displayFolder: Info

	column 'Order ID'
		dataType: string
		summarizeBy: none
		sourceColumn: Order ID

	column 'Order Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: Order Date

	column 'Store ID'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Store ID

	column 'Product ID'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Product ID

	column Quantity
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: Quantity

	column 'Unit Price'
		dataType: double
		formatString: $#,0.00
		summarizeBy: none
		sourceColumn: Unit Price

	column Discount
		dataType: double
		formatString: 0%
		summarizeBy: none
		sourceColumn: Discount

	column 'Net Sales'
		dataType: double
		formatString: $#,0
		summarizeBy: sum
		sourceColumn: Net Sales

	column COGS
		dataType: double
		formatString: $#,0
		summarizeBy: sum
		sourceColumn: COGS

	partition Orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Orders.csv"), [Delimiter = ",", Columns = 9, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Order ID", type text}, {"Order Date", type date}, {"Store ID", type text}, {"Product ID", type text}, {"Quantity", Int64.Type}, {"Unit Price", type number}, {"Discount", type number}, {"Net Sales", type number}, {"COGS", type number}}, "en-US")
				in
				    Typed
