table Stores

	column 'Store ID'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Store ID

	column Store
		dataType: string
		summarizeBy: none
		sourceColumn: Store

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region

	column Channel
		dataType: string
		summarizeBy: none
		sourceColumn: Channel

	partition Stores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Stores.csv"), [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"Store ID", type text}, {"Store", type text}, {"City", type text}, {"Region", type text}, {"Channel", type text}}, "en-US")
				in
				    Typed
